### ISSUE TITLE
FileNotFoundError on MacOS as it is expecting ~/.cache directory

### ISSUE THREAD

**Issue by adeekshith** [npiv/chatblade#11]
```
$ chatblade how can I extract a still frame from a video at 22:01 with ffmpeg
Traceback (most recent call last):
  File "/opt/homebrew/bin/chatblade", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/chatblade/__main__.py", line 5, in main
    cli.cli()
  File "/opt/homebrew/lib/python3.11/site-packages/chatblade/cli.py", line 170, in cli
    messages = fetch_and_cache(messages, params)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/chatblade/cli.py", line 135, in fetch_and_cache
    to_cache(messages)
  File "/opt/homebrew/lib/python3.11/site-packages/chatblade/cli.py", line 113, in to_cache
    with open(path, "wb") as f:
         ^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/Users/myusername/.cache/chatblade'
```

Running `mkdir ~/.cache` fixed the issue but just filing this so we can add a check in the code to see if the cache directory exists.

**Comment by adeekshith** [comment]
Code likely where changes need to be made: https://github.com/npiv/chatblade/blob/main/chatblade/cli.py#L107-L129
