### ISSUE TITLE
ModuleNotFoundError: No module named ‘platformdirs'

### ISSUE THREAD

**Issue by kseistrup** [npiv/chatblade#13]
On a fresh pip install from the git repo here, chatblade complains that `platformdirs` is missing.

Python 3.10.10 in a virtual environment contining only `pip`, `wheel`, and `setuptools` before installing.

**Comment by alesr** [comment]
Same issue here.

```shell
λ chatblade hello
Traceback (most recent call last):
  File "/Users/alesr/Library/Python/3.9/bin/chatblade", line 5, in <module>
    from chatblade.__main__ import main
  File "/Users/alesr/Library/Python/3.9/lib/python/site-packages/chatblade/__main__.py", line 1, in <module>
    from . import cli
  File "/Users/alesr/Library/Python/3.9/lib/python/site-packages/chatblade/cli.py", line 8, in <module>
    from . import printer, chat, utils, storage
  File "/Users/alesr/Library/Python/3.9/lib/python/site-packages/chatblade/storage.py", line 7, in <module>
    import platformdirs
ModuleNotFoundError: No module named 'platformdirs'
```

**Comment by npiv** [comment]
my bad, it was only added to requirements.txt this morning. Should be fixed - please try agin.
