### ISSUE TITLE
Better error handling

### ISSUE THREAD

**Issue by bdmbdsm** [npiv/chatblade#15]
When I run this example command:

`chatblade "is casio f-91w a good watch?" -c 4`

I receive following output:

```
Traceback (most recent call last):
  File "/home/bdmbdsm/.local/share/virtualenvs/chat-X6P-Bc3p/bin/chatblade", line 8, in <module>
    sys.exit(main())
  File "/home/bdmbdsm/.local/share/virtualenvs/chat-X6P-Bc3p/lib/python3.10/site-packages/chatblade/__main__.py", line 5, in main
    cli.cli()
  File "/home/bdmbdsm/.local/share/virtualenvs/chat-X6P-Bc3p/lib/python3.10/site-packages/chatblade/cli.py", line 164, in cli
    handle_input(query, params)
  File "/home/bdmbdsm/.local/share/virtualenvs/chat-X6P-Bc3p/lib/python3.10/site-packages/chatblade/cli.py", line 154, in handle_input
    messages = fetch_and_cache(messages, params)
  File "/home/bdmbdsm/.local/share/virtualenvs/chat-X6P-Bc3p/lib/python3.10/site-packages/chatblade/cli.py", line 107, in fetch_and_cache
    response_msg, _ = chat.query_chat_gpt(messages, params)
  File "/home/bdmbdsm/.local/share/virtualenvs/chat-X6P-Bc3p/lib/python3.10/site-packages/chatblade/chat.py", line 44, in query_chat_gpt
    result = openai.ChatCompletion.create(messages=dict_messages, **config)
  File "/home/bdmbdsm/.local/share/virtualenvs/chat-X6P-Bc3p/lib/python3.10/site-packages/openai/api_resources/chat_completion.py", line 25, in create
    return super().create(*args, **kwargs)
  File "/home/bdmbdsm/.local/share/virtualenvs/chat-X6P-Bc3p/lib/python3.10/site-packages/openai/api_resources/abstract/engine_api_resource.py", line 153, in create
    response, _, api_key = requestor.request(
  File "/home/bdmbdsm/.local/share/virtualenvs/chat-X6P-Bc3p/lib/python3.10/site-packages/openai/api_requestor.py", line 226, in request
    resp, got_stream = self._interpret_response(result, stream)
  File "/home/bdmbdsm/.local/share/virtualenvs/chat-X6P-Bc3p/lib/python3.10/site-packages/openai/api_requestor.py", line 619, in _interpret_response
    self._interpret_response_line(
  File "/home/bdmbdsm/.local/share/virtualenvs/chat-X6P-Bc3p/lib/python3.10/site-packages/openai/api_requestor.py", line 682, in _interpret_response_line
    raise self.handle_error_response(
openai.error.InvalidRequestError: The model: `gpt-4` does not exist
```

Perhaps that's not a high priority thing, but it would be nice to show that error through rich & without all that stacktrace.

**Comment by npiv** [comment]
I will leave the stacktraces for unexpected events as it's easier to debug when people have issues. 

But it seems many people run into gpt-4 not available so openai.error.InvalidRequestError is handled more gracefully
