### ISSUE TITLE
Using CTRL-D in interactive mode throws an EOFError

### ISSUE THREAD

**Issue by hashworks** [npiv/chatblade#19]
```
query (type 'quit' to exit): : Foo
╭──────────────────────────────────────────────────────── assistant ────────────────────────────────────────────────────────╮
│ Bar                                                                                                                       │
╰───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
query (type 'quit' to exit): : <CTRL-D>
Traceback (most recent call last):
  File "/usr/bin/chatblade", line 33, in <module>
    sys.exit(load_entry_point('chatblade==0.0.2', 'console_scripts', 'chatblade')())
  File "/usr/lib/python3.10/site-packages/chatblade/__main__.py", line 5, in main
    cli.cli()
  File "/usr/lib/python3.10/site-packages/chatblade/cli.py", line 164, in cli
    handle_input(query, params)
  File "/usr/lib/python3.10/site-packages/chatblade/cli.py", line 144, in handle_input
    start_repl(None, params)
  File "/usr/lib/python3.10/site-packages/chatblade/cli.py", line 116, in start_repl
    query = Prompt.ask("[yellow]query (type 'quit' to exit): [/yellow]")
  File "/usr/lib/python3.10/site-packages/rich/prompt.py", line 141, in ask
    return _prompt(default=default, stream=stream)
  File "/usr/lib/python3.10/site-packages/rich/prompt.py", line 274, in __call__
    value = self.get_input(self.console, prompt, self.password, stream=stream)
  File "/usr/lib/python3.10/site-packages/rich/prompt.py", line 203, in get_input
    return console.input(prompt, password=password, stream=stream)
  File "/usr/lib/python3.10/site-packages/rich/console.py", line 2123, in input
    result = input()
EOFError
```

CTRL-D is often used to quit interactive prompts, so it shouldn't throw an error.

**Comment by npiv** [comment]
fixed
