### ISSUE TITLE
FileExistsError on Windows

### ISSUE THREAD

**Issue by Bubblegits** [npiv/chatblade#39]
Thank you for developing this tool, it has been very helpful. However, I have encountered issues with the session feature while using it on Windows. When starting a query, an error message appears as follows:

```
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "E:\python\Scripts\chatblade.exe\__main__.py", line 7, in <module>
  File "E:\python\Lib\site-packages\chatblade\__main__.py", line 5, in main
    cli.cli()
  File "E:\python\Lib\site-packages\chatblade\cli.py", line 152, in cli
    handle_input(query, params)
  File "E:\python\Lib\site-packages\chatblade\cli.py", line 81, in handle_input
    messages = fetch_and_cache(messages, params)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\python\Lib\site-packages\chatblade\cli.py", line 26, in fetch_and_cache
    storage.to_cache(messages, params.session or utils.scratch_session)
  File "E:\python\Lib\site-packages\chatblade\storage.py", line 56, in to_cache
    os.rename(file_path_tmp, file_path)
FileExistsError: [WinError 183] 当文件已存在时，无法创建该文件。: 'C:\\Users\\qipao\\AppData\\Local\\chatblade\\chatblade\\Cache\\chatblade\\last.yaml.eDdQy479DK' -> 'C:\\Users\\qipao\\AppData\\Local\\chatblade\\chatblade\\Cache\\chatblade\\last.yaml'
```

It says that you can not create a file when it already exists. I tried on my mac and everything goes well. Can this be fixed?

**Comment by npiv** [comment]
I have access to a windows machine next week, will replicate and fix.

**Comment by nivkovic78** [comment]
Same issue

**Comment by npiv** [comment]
should be fixed in latest v0.2.2
