### ISSUE TITLE
error providing prompt file

### ISSUE THREAD

**Issue by shedali** [npiv/chatblade#41]
trying to use prompt file with chatblade (tried installation with via pip, brew, tea)

```bash
chatblade -p testing hello 

$ Prompt ~/.config/chatblade/testing not found in ~/.config/chatblade/testing.yaml

echo $PROMPT > ~/.config/chatblade/testing

chatblade -p testing hello

Traceback (most recent call last):
  File "/opt/homebrew/bin/chatblade", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/opt/homebrew/Cellar/chatblade/0.0.2/libexec/lib/python3.11/site-packages/chatblade/__main__.py", line 5, in main
    cli.cli()
  File "/opt/homebrew/Cellar/chatblade/0.0.2/libexec/lib/python3.11/site-packages/chatblade/cli.py", line 164, in cli
    handle_input(query, params)
  File "/opt/homebrew/Cellar/chatblade/0.0.2/libexec/lib/python3.11/site-packages/chatblade/cli.py", line 139, in handle_input
    messages = chat.init_conversation(query, prompt_config["system"])
                                             ~~~~~~~~~~~~~^^^^^^^^^^
TypeError: 'NoneType' object is not subscriptable
error

$ Prompt ~/.config/chatblade/testing not found in ~/.config/chatblade/testing.yaml
```

**Comment by npiv** [comment]
v`0.0.2` is quite outdated.

The current version of chatblade is `0.2.2`. I have bumped the brew version, if you try again with homebrew it should pick it up. Let me know if you still have the issue after moving up to 0.2.2

**Comment by shedali** [comment]
thanks @npiv , updated to 0.2.3 and see same error
