### ISSUE TITLE
[Feature request] Package for Homebrew

### ISSUE THREAD

**Issue by hmontazeri** [npiv/chatblade#5]

**Comment by mardoqueo** [comment]
pretty please

**Comment by chrisfinazzo** [comment]
Beat me to it.

If not Homebrew itself, at least pipx would be nice.

From there, you could do `brew install pipx && pipx install chatblade` and you're off to the races.

**Comment by npiv** [comment]
I tried but homebrew official repo doesnt allow brews on a repository that is less than 30d old. So you will have to wait 28 days.

Alternatively you can try a hombrew tap I set up:
`brew install npiv/chatblade/chatblade`

Its slower than an offical homebrew tap as it builds everything from source, so grab a coffee :)

Would be good to hear if its working for others. The 30d wait is out of my hands

**Comment by chrisfinazzo** [comment]
> Its slower than an official homebrew tap as it builds everything from source.

Not untrue. Took about 20 minutes to compile but felt like...

![eternity](https://user-images.githubusercontent.com/1534882/226926396-cc39f353-69a3-41df-bbd1-0e03eaab579c.jpg)

That aside, I didn't expect to be rate-limited immediately after setting an API key:

```
Traceback (most recent call last):
  File "/usr/local/bin/chatblade", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/local/Cellar/chatblade/0.0.2/libexec/lib/python3.11/site-packages/chatblade/__main__.py", line 5, in main
    cli.cli()
  File "/usr/local/Cellar/chatblade/0.0.2/libexec/lib/python3.11/site-packages/chatblade/cli.py", line 164, in cli
    handle_input(query, params)
  File "/usr/local/Cellar/chatblade/0.0.2/libexec/lib/python3.11/site-packages/chatblade/cli.py", line 154, in handle_input
    messages = fetch_and_cache(messages, params)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/chatblade/0.0.2/libexec/lib/python3.11/site-packages/chatblade/cli.py", line 107, in fetch_and_cache
    response_msg, _ = chat.query_chat_gpt(messages, params)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/chatblade/0.0.2/libexec/lib/python3.11/site-packages/chatblade/chat.py", line 68, in query_chat_gpt
    result = openai.ChatCompletion.create(messages=dict_messages, **config)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/chatblade/0.0.2/libexec/lib/python3.11/site-packages/openai/api_resources/chat_completion.py", line 25, in create
    return super().create(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/chatblade/0.0.2/libexec/lib/python3.11/site-packages/openai/api_resources/abstract/engine_api_resource.py", line 153, in create
    response, _, api_key = requestor.request(
                           ^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/chatblade/0.0.2/libexec/lib/python3.11/site-packages/openai/api_requestor.py", line 226, in request
    resp, got_stream = self._interpret_response(result, stream)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/chatblade/0.0.2/libexec/lib/python3.11/site-packages/openai/api_requestor.py", line 619, in _interpret_response
    self._interpret_response_line(
  File "/usr/local/Cellar/chatblade/0.0.2/libexec/lib/python3.11/site-packages/openai/api_requestor.py", line 682, in _interpret_response_line
    raise self.handle_error_response(
openai.error.RateLimitError: You exceeded your current quota, please check your plan and billing details.
```

**Comment by npiv** [comment]
Anyone here familiar with tea.xyz: https://github.com/npiv/chatblade/pull/23

Not sure about this PR, it is claimed to be by the hombrew creator, never used it myself

**Comment by magnusviri** [comment]
> Anyone here familiar with tea.xyz: #23
> 
> Not sure about this PR, it is claimed to be by the hombrew creator, never used it myself

[Tea](https://github.com/teaxyz/cli/graphs/contributors) is indeed [by the creator of Homebrew.](https://github.com/Homebrew/brew/commits?author=mxcl&since=2009-05-17&until=2009-12-11). I'm a volunteer involved with tea, so I'm not exactly an impartial observer.

**Comment by npiv** [comment]
brew supported, see readme
