### ISSUE TITLE
TypeError: __str__ returned non-string (type dict)

### ISSUE THREAD

**Issue by johnd0e** [npiv/chatblade#59]
```
Traceback (most recent call last):
  File "D:\OpenAI\chatblade\venv\lib\site-packages\chatblade\chat.py", line 122, in query_chat_gpt
    result = openai.ChatCompletion.create(messages=dict_messages, **config)
  File "D:\OpenAI\chatblade\venv\lib\site-packages\openai\api_resources\chat_completion.py", line 25, in create
    return super().create(*args, **kwargs)
  File "D:\OpenAI\chatblade\venv\lib\site-packages\openai\api_resources\abstract\engine_api_resource.py", line 153, in create
    response, _, api_key = requestor.request(
  File "D:\OpenAI\chatblade\venv\lib\site-packages\openai\api_requestor.py", line 298, in request
    resp, got_stream = self._interpret_response(result, stream)
  File "D:\OpenAI\chatblade\venv\lib\site-packages\openai\api_requestor.py", line 700, in _interpret_response
    self._interpret_response_line(
  File "D:\OpenAI\chatblade\venv\lib\site-packages\openai\api_requestor.py", line 765, in _interpret_response_line
    raise self.handle_error_response(
openai.error.AuthenticationError: <exception str() failed>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\a\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\a\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "D:\OpenAI\chatblade\venv\Scripts\chatblade.exe\__main__.py", line 7, in <module>
  File "D:\OpenAI\chatblade\venv\lib\site-packages\chatblade\__main__.py", line 5, in main
    cli.cli()
  File "D:\OpenAI\chatblade\venv\lib\site-packages\chatblade\cli.py", line 152, in cli
    handle_input(query, params)
  File "D:\OpenAI\chatblade\venv\lib\site-packages\chatblade\cli.py", line 81, in handle_input
    messages = fetch_and_cache(messages, params)
  File "D:\OpenAI\chatblade\venv\lib\site-packages\chatblade\cli.py", line 14, in fetch_and_cache
    result = chat.query_chat_gpt(messages, params)
  File "D:\OpenAI\chatblade\venv\lib\site-packages\chatblade\chat.py", line 136, in query_chat_gpt
    raise errors.ChatbladeError(f"openai error: {e}")
TypeError: __str__ returned non-string (type dict)
```

Indeed `__str__` returns dict:
```py
{'code': 'account_deactivated', 'message': 'Your OpenAI account has been deactivated, please check your email for more information. If you feel this is an error, contact us through our help center at help.openai
.com.', 'param': None, 'type': 'invalid_request_error'}
```

**Comment by npiv** [comment]
Hi @johnd0e,

I think the msg is clear right? 

```Your OpenAI account has been deactivated, please check your email for more information. If you feel this is an error, contact us through our help center at help.openai.com.```

This is an issue you will have to resolve with them, your API key has been de-activated

**Comment by johnd0e** [comment]
But it is not message - it is unhandled Exception, which means there is an error (either in chatblade, or in openai API).

About my account - it is not really mine, in fact I'm using reverse proxy which rotates a pool of different API keys. Some of them get invalidated, but I have no control on that.

So it really would be good to see proper error message, instead of unhandled exception.
