### ISSUE TITLE
Crash on calling chatblade -e

### ISSUE THREAD

**Issue by nukeop** [npiv/chatblade#7]
Example screenshot:
![image](https://user-images.githubusercontent.com/12746779/226386591-18745bfe-a616-4b1d-b7db-1cd25fdec99b.png)

Is there any way I can solve this myself?

**Comment by kalasbralla** [comment]
Still experiencing the same error. 

Traceback (most recent call last):
  File "/home/username/.local/bin/chatblade", line 8, in <module>
    sys.exit(main())
  File "/home/username/.local/lib/python3.10/site-packages/chatblade/__main__.py", line 5, in main
    cli.cli()
  File "/home/username/.local/lib/python3.10/site-packages/chatblade/cli.py", line 155, in cli
    printer.print_messages(messages, params)
  File "/home/username/.local/lib/python3.10/site-packages/chatblade/printer.py", line 35, in print_messages
    extract_messages(messages, args)
  File "/home/username/.local/lib/python3.10/site-packages/chatblade/printer.py", line 57, in extract_messages
    elif contains_block(message.content):
  File "/home/username/.local/lib/python3.10/site-packages/chatblade/printer.py", line 81, in contains_block
    if extract_block(str):
  File "/home/username/.local/lib/python3.10/site-packages/chatblade/printer.py", line 88, in extract_block
    return sorted(matches, key=lambda x: len(x))[-1].strip()
IndexError: list index out of range

**Comment by nukeop** [comment]
Thanks for fixing it so fast!
