### ISSUE TITLE
model: gpt-4 does not exist

### ISSUE THREAD

**Issue by tomsib2001** [npiv/chatblade#9]
Commit used: 4ce28739ca7ada161102917ad256d3db61026392

```shell
file.md | chatblade continue this -c 4                                                                                      │
│                                                                                                                                                                                       │
│ Traceback (most recent call last): File "/my/home/.local/bin/chatblade", line 8, in <module> sys.exit(main()) File "/my/home/.local/lib/python3.10/site-packages/chatblade/main.py",  │
│ line 5, in main cli.cli() File "/my/home/.local/lib/python3.10/site-packages/chatblade/cli.py", line 154, in cli messages = fetch_and_cache(messages, params) File                    │
│ "/my/home/.local/lib/python3.10/site-packages/chatblade/cli.py", line 126, in fetch_and_cache response_msg, _ = chat.query_chat_gpt(messages, params) File                            │
│ "/my/home/.local/lib/python3.10/site-packages/chatblade/chat.py", line 44, in query_chat_gpt result = openai.ChatCompletion.create(messages=dict_messages, **config) File             │
│ "/my/home/.local/lib/python3.10/site-packages/openai/api_resources/chat_completion.py", line 25, in create return super().create(*args, **kwargs) File                                │
│ "/my/home/.local/lib/python3.10/site-packages/openai/api_resources/abstract/engine_api_resource.py", line 153, in create response, _, api_key = requestor.request( File               │
│ "/my/home/.local/lib/python3.10/site-packages/openai/api_requestor.py", line 226, in request resp, got_stream = self._interpret_response(result, stream) File                         │
│ "/my/home/.local/lib/python3.10/site-packages/openai/api_requestor.py", line 619, in _interpret_response self._interpret_response_line( File                                          │
│ "/my/home/.local/lib/python3.10/site-packages/openai/api_requestor.py", line 682, in _interpret_response_line raise self.handle_error_response( openai.error.InvalidRequestError: The │
│ model: gpt-4 does not exist
```

**Comment by npiv** [comment]
gpt-4 is not fully public yet, you need to join the waitlist.

`curl https://api.openai.com/v1/models -H "Authorization: Bearer $OPENAI_API_KEY" | grep "gpt-"`

If the output of that doesn't show you gpt-4, you don't have access yet.
